name: Feature Idea / Request
description: Suggest an idea for this project
title: "[Suggestion]: "
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: Explain your idea
      description: Tell me what you want to be implemented here
      placeholder: I would like to have an command for XYZ
      value: "I have an idea!"
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: If this is platform-dependant, which platform is this about?
      multiple: true
      options:
        - Forge
        - Spigot
