name: Question
description: Ask an question about this project
title: "[Question]: "
labels: [question]
body:
  - type: textarea
    id: description
    attributes:
      label: 
      description: Ask your Question here
      placeholder: How do I set up XYZ?
      value: "Can I ask you something?"
    validations:
      required: true
